### ISSUE TITLE
Rewrite GJS plugins in Rust

### ISSUE THREAD

**Issue by mmstick** [pop-os/launcher#1]
- [x] Calculator (Switched from Math.JS to Qalc)
- [x] Desktop Entries
- [x] File Browser
- [x] File Find
- [ ] PulseAudio
- [ ] Recent Files
- [x] Scripts
- [ ] Terminal
- [x] Web

**Comment by jacobgkau** [comment]
I don't want to edit your comment for you, but the remaining three items on the list (PulseAudio, Recent Files, and Terminal) are all working in the Rust launcher, so I believe this issue can be closed.
