### ISSUE TITLE
Gnome extensions doesn't open

### ISSUE THREAD

**Issue by msdrigg** [pop-os/launcher#10]
When I use the pop-os launcher, I can search "Extensions" and the Gnome extensions application is found. 

When I click on this link in the launcher, nothing happens. I am seeing this error appear in journalctl, but I don't know if it is related 

> pop-os gnome-shell[2445]: Could not create transient scope for PID 116180: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 116180 does not exist.

I can use the "Show Applications" menu to launch Gnome extensions, and it works fine. This issue only happens when I try to use the launcher.

**Comment by mmstick** [comment]
This was already fixed by #9
