### ISSUE TITLE
Shortcuts Ctrl + J/K does not work when Caps Lock is ON

### ISSUE THREAD

**Issue by senntore** [pop-os/launcher#102]
**Issue:** Shortcuts for navigating up/down in the launcher, Ctrl + J/K does not work

**pop-launcher version:**
```
pop-launcher:
  Installed: 1.2.1~1648660013~21.10~0893990
  Candidate: 1.2.1~1648660013~21.10~0893990
  Version table:
 *** 1.2.1~1648660013~21.10~0893990 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
        100 /var/lib/dpkg/status

```
**Pop OS:** 21.10 & now 22.04
**Other notes**: Other shortcuts like TAB & arrow keys seems to work as usual when Caps Lock is ON.

**Comment by jmbuhr** [comment]
I'm on the latest pop os (22.04) and now most shortcuts don't work anymore.
No `ctrl+j/k`, no `tab`, no `ctrl+number`.
The only thing that seems to work is `ctrl+shift+tab`

**Comment by senntore** [comment]
> I'm on the latest pop os (22.04) and now most shortcuts don't work anymore. No `ctrl+j/k`, no `tab`, no `ctrl+number`. The only thing that seems to work is `ctrl+shift+tab`
@jmbuhr 
I'm on 22.04 as well but I can't reproduce (your)issues other than the stuff I mentioned in the title, meaning those shortcut work fine for me.

**Comment by jmbuhr** [comment]
oh, interesting!
