### ISSUE TITLE
[Suggestion] Use a query that begins with "." to start file navigation from the home folder

### ISSUE THREAD

**Issue by mijorus** [pop-os/launcher#104]
Why?

I think file navigation autocomplete is a very cool feature,  but there are some "problems" that prevent me from using it:

1. Most of the time, I'm searching for something in the home folder, which requires pressing 3 buttons just enable it (shift + ~ and /)
2. An italian keyboard does not have the ~  key, making it even harder as I need to press like 4  buttons before I can get there.

My suggestion would be to use something like "." to trigger file navigation from the home folder, which is generally easier to reach on any keyboard layout.

**Comment by oknozor** [comment]
Hey @mijorus you can do it by modifying the files plugin configuration.
It's either located in `$HOME/.local/share/pop-launcher/plugins/files/plugin.ron` or `/usr/lib//pop-launcher/plugins/files/plugin.ron` depending on how you installed pop-launcher. 

All you need is to adjust the regex to `regex: "^(.).*"`

**Comment by mijorus** [comment]
The regex you proposed matches any character, the correct one would be `^(\.).*` (which does not work either)
