### ISSUE TITLE
[22.04] No Right click menu

### ISSUE THREAD

**Issue by 13r0ck** [pop-os/launcher#105]
The right click menu doesn't show after right clicking

**Comment by canadaduane** [comment]
Is there any more info regarding what is intended with this right-click menu? Is this a regression? Or perhaps something that has been visually designed but not yet implemented?

**Comment by curiousercreative** [comment]
Has this been resolved? On the latest Pop, I get the right click menu.

**Comment by leviport** [comment]
I believe it has, thanks for the reminder
