### ISSUE TITLE
Launcher is not triggered when current app is in full screen mode

### ISSUE THREAD

**Issue by hiredgunhouse** [pop-os/launcher#146]
Make Firefox run in full-screen mode by hitting F11 and then the Super key does not work, meaning launcher is not triggered.

**Comment by n3m0-22** [comment]
There is a setting in the Pop Shell extension that you may need to toggle.

Open `Extensions`
Find `Pop Shell` and select `Settings`
Enable `Allow launcher over fullscreen window`

![Screenshot from 2022-10-27 05-21-27](https://user-images.githubusercontent.com/11048214/198273048-801a015f-7b1e-4c26-8dab-a3589670871c.png)

![Screenshot from 2022-10-27 05-21-38](https://user-images.githubusercontent.com/11048214/198273074-f799eb94-2b7c-4e26-87df-7464ea47f305.png)

**Comment by n3m0-22** [comment]
I'm closing this issue, but can reopen it if this did not solve it for you.
