### ISSUE TITLE
support directory search

### ISSUE THREAD

**Issue by jqhr** [pop-os/launcher#150]
I like launcher very much. Most of my works need。
But I have many front-end projects. you now,  with thousands of node_modules packages.
They confuse me when I use launcher to find my project, (for example, I want to enter one of projects, but I cannot search my project name)
So I need it very much.

**Comment by n3m0-22** [comment]
To search through directories you can use `/`. If you want to search in your home directory you can use `~/` or `/home/(your-user-name-here)`. This should show the files and folders. You can start typing the name you are looking for (files and folders) here, and use the arrow keys to to select them. You can use `Tab` on the selected item, and it will autocomplete into the search box. If you want to check for other launcher functionality you can type `?`. Does this accomplish what you are try to do?

**Comment by leviport** [comment]
There is also the `find` keyword for searching, as opposed to navigating through the filesystem.

**Comment by jqhr** [comment]
> There is also the `find` keyword for searching, as opposed to navigating through the filesystem.

Yes, but find command only support for file, not directory.
Em,  sometimes, I want  find the directory of the file.

**Comment by jqhr** [comment]
> To search through directories you can use `/`. If you want to search in your home directory you can use `~/` or `/home/(your-user-name-here)`. This should show the files and folders. You can start typing the name you are looking for (files and folders) here, and use the arrow keys to to select them. You can use `Tab` on the selected item, and it will autocomplete into the search box. If you want to check for other launcher functionality you can type `?`. Does this accomplish what you are try to do?

Em, I want to find the file' directory. For directory navigate, it only support one level. but I need all of sub directory for current path.

**Comment by canadaduane** [comment]
@jqhr I believe PR #161 is what you are looking for.

**Comment by jqhr** [comment]
@canadaduane 
Thanks for your contribute.I do need this pr
