### ISSUE TITLE
Feature Request: Lock screen option

### ISSUE THREAD

**Issue by btegs** [pop-os/launcher#165]
If I open up the Launcher and type any of these, they will work:

* Log Out
* Power Off/Shutdown
* Restart
* Suspend

But if I type **Lock**, I do not see the option to Lock the screen. Is this something planned or easy to implement? Just a little quality of life thingie :-)

**Comment by n3m0-22** [comment]
I've created a PR #166 that will need to be reviewed and tested. In the meantime you can lock the screen with `Super` + `Esc`.

You can also make your own script for the time being with the following commands.

- `touch ~/.local/share/pop-launcher/scripts/session/lock-screen.sh`
- `gedit ~/.local/share/pop-launcher/scripts/session/lock-screen.sh`

- In the file that opens paste the following:

```
#!/usr/bin/sh
#
# name: Lock
# icon: locked
# description: Lock the system
# keywords: lock
 
set -eu
 
loginctl lock-session
```
- Save the file

- `sudo chmod a+x ~/.local/share/pop-launcher/scripts/session/lock-screen.sh`

**Comment by leviport** [comment]
Closing since https://github.com/pop-os/launcher/pull/166 was merged. It should be released some time this week.

**Comment by btegs** [comment]
Thanks for your contributions everyone!
