### ISSUE TITLE
Launcher does not work

### ISSUE THREAD

**Issue by dharmik2319** [pop-os/launcher#177]
**(1) Issue/Bug Description:**
When pressing `super`, the launcher window does show up, but is empty, and does not show running apps, and also cannot search apps, or basically anything (like the calculator with the `=` key). Even `?` doesn't work, it still remains empty.

**(2) Expected behavior:**
Launcher shows all running apps and searchable apps and functions normally, as it would.

**(3) Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
**(4) Gnome Shell version:**
`gnome-shell --version` reports `GNOME Shell 42.5`

**(5) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```pop-shell:
  Installed: 1.1.0~1677211888~22.04~dcf17f3
  Candidate: 1.1.0~1677211888~22.04~dcf17f3
  Version table:
 *** 1.1.0~1677211888~22.04~dcf17f3 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```
```
pop-launcher:
  Installed: 1.2.2~1678935224~22.04~717fd61
  Candidate: 1.2.2~1678935224~22.04~717fd61
  Version table:
 *** 1.2.2~1678935224~22.04~717fd61 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**(6) Where was Pop Shell/Launcher installed from:**
Preinstalled and updated, not from source

**(7) Other Installed/Enabled Extensions:**
`gnome-extensions list --enabled` reports:
```
clipboard-indicator@tudmotu.com
dash-to-dock-cosmic-@halfmexicanhalfamazing@gmail.com
emoji-selector@maestroschan.fr
compiz-windows-effect@hermes83.github.com
cosmic-workspaces@system76.com
ding@rastersoft.com
pop-cosmic@system76.com
pop-shell@system76.com
system76-power@system76.com
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
```

**(8) Other Notes:**
`pop-launcher` reports:
```
[1]    33278 illegal hardware instruction (core dumped)  pop-launcher
```

and the issue has been persisting since about a month or so

**Comment by dharmik2319** [comment]
I would like to add that I would like to not build from source, as I am low on storage and my device is low-end

**Comment by dharmik2319** [comment]
Some screenshots:
![image](https://user-images.githubusercontent.com/126943942/227473936-900b8552-2076-4489-ba86-448edcbe1708.png)
![Screenshot from 2023-03-24 14-33-51](https://user-images.githubusercontent.com/126943942/227474102-14de5f16-67f5-4fb0-9555-2b425f115132.png)
![Screenshot from 2023-03-24 14-33-40](https://user-images.githubusercontent.com/126943942/227474120-c0f354bf-b74d-4a11-a06a-93ab51566944.png)
![Screenshot from 2023-03-24 14-33-18](https://user-images.githubusercontent.com/126943942/227474136-4bbc83f5-6924-40c4-9ce9-7ef1bfd4bdf1.png)

**Comment by leviport** [comment]
It looks like you've made some extensive aesthetic modifications to your installation. Have you ruled those out as a cause?

**Comment by dharmik2319** [comment]
I have now disabled most extensions, except the essential ones, and now, `gnome-extensions list --enabled` returns:
```
dash-to-dock-cosmic-@halfmexicanhalfamazing@gmail.com
cosmic-workspaces@system76.com
pop-cosmic@system76.com
pop-shell@system76.com
system76-power@system76.com
```

I have also tried restarting the shell with `Alt+F2` and `r`, but the issue still persists.
Also, is there are other steps/tests that you want me to take, please mention them together, so that time is saved for the both of us.

**Comment by dharmik2319** [comment]
Are you able to diagnose the cause of this? Or do you need me to try out more things?

**Comment by dharmik2319** [comment]
@leviport, do you think it might be related to 
> **(8) Other Notes:**
`pop-launcher` reports:
```
[1]    33278 illegal hardware instruction (core dumped)  pop-launcher
```

**Comment by leviport** [comment]
That doesn't really tell me anything, but if we're worried about some kind of hardware incompatibility, you could boot a live disk to see if the launcher works in a clean environment. My bet is that it will, and if it does, that means something is misconfigured in your installation.

**Comment by dharmik2319** [comment]
Do you have some idea, as to what the misconfiguration might be? So that it is easier for me to try to solve this.

**Comment by mmstick** [comment]
You could check if the launcher package from staging/master works

**Comment by dharmik2319** [comment]
Ok, so I tied compiling v1.2.1 and v1.2.2
I did a local install
when I tried to execute the v1.2.2 binary, it said 
```
could not read cache file
No such file or directory
```

when i executed the v1.2.2 binary, there was no output at all, and the process just continued till i stopped it with `Ctrl+c`.

**Comment by dharmik2319** [comment]
you may decide if you wish to close this, or solve the weird behaviour
