### ISSUE TITLE
'find' lists files but wont open them

### ISSUE THREAD

**Issue by valentingar** [pop-os/launcher#179]
Some time ago, my pop-launcher stopped opening files that are found by typing `find my_file`. Could this be a permission issue? I am unfortunately not very experienced using Linux, so any help fixing this issue would be much appreciated! 

I don't have any custom plugins installed for the pop-launcher. Here is some info on the system: 

output from `cat /etc/os-release`
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

output from `apt policy pop-shell`
```
pop-shell:
  Installed: 1.1.0~1680708801~22.04~a3a1b7b
  Candidate: 1.1.0~1680708801~22.04~a3a1b7b
  Version table:
 *** 1.1.0~1680708801~22.04~a3a1b7b 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

output from `apt policy pop-launcher`
```
pop-launcher:
  Installed: 1.2.2~1679671233~22.04~ce2ba21
  Candidate: 1.2.2~1679671233~22.04~ce2ba21
  Version table:
 *** 1.2.2~1679671233~22.04~ce2ba21 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by valentingar** [comment]
Wow. I found the problem. 

**Problem**
The problem also was present when trying to open any file or folder from the Desktop. 
So I noticed that running 
`xdg-open path_to_any_file` 
in the terminal yielded an error 
`"WSL Interopability is disabled. Please enable it before using WSL."`

**Solution:**
Running
 `sudo apt purge wslu`
as per [this thread](https://askubuntu.com/questions/1422920/how-does-one-enable-wsl-interoperability-on-ubuntu-22-04) removed both the error message in the terminal and fixed the error in the pop launcher and dekstop.

**Comment by jacobgkau** [comment]
Just to be clear, are you running the launcher in a Windows environment using WSL?
