### ISSUE TITLE
Espanso detect "active application information" blank

### ISSUE THREAD

**Issue by synvie92** [pop-os/launcher#187]
Platform : Pop!OS 20.04
Espanso: 2.1.8

blank information when i type `#detect#` on Pop Launcher box

![image](https://github.com/pop-os/launcher/assets/21971195/f8bc445b-4a6e-4b86-99a2-9df6be17126e)

Reference Step:
https://espanso.org/docs/configuration/app-specific-configurations/#finding-the-right-filters

**Comment by mmstick** [comment]
It's not a window, but a gnome-shell dialog. Also, the correct repo would be pop-os/shell
