### ISSUE TITLE
Desktop entries deduplication

### ISSUE THREAD

**Issue by friday** [pop-os/launcher#19]
> If multiple files have the same desktop file ID, the first one in the $XDG_DATA_DIRS precedence order is used.
- https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s02.html#desktop-file-id

Currently I have Nautilus duplicated in these two directories:
* `~/.local/share/applications/org.gnome.Nautilus.desktop`
* `/usr/share/applications/org.gnome.Nautilus.desktop`

I do this to override something in the desktop entries and avoid rewriting it when I update the package it belongs to.

My xdg_data_dirs: `~/.local/share`, `/usr/local/share` and `/usr/share` (`XDG_DATA_DIRS` is actually not set, but these are the paths that should be used when this is the case)

![Screenshot from 2021-09-13 21-03-38](https://user-images.githubusercontent.com/515120/133141895-16539c95-dd24-4d14-957a-31d14d862040.png)

(same thing with "Bulk Rename", which is part of Thunar).

If you want this I could try to implement it, but I'm a Rust noob at best and haven't looked into your code.

**Comment by mmstick** [comment]
There's currently a Set collection that's filtering based on source and app ID. Removing the Hash and PartialEq condition for the `src` field would have it only consider the app ID. You would simply have to ensure that the local apps have a higher priority in the set than system apps.

**Comment by friday** [comment]
Nice. Thank you for the pointers :+1:

**Comment by friday** [comment]
Awesome! Real life and other things got in between, so I never had the chance to start looking at it, but hope to be able to contribute soon :)
