### ISSUE TITLE
Proposal : Adding Launcher Themes to Pop Launcher

### ISSUE THREAD

**Issue by shivamksharma** [pop-os/launcher#196]
I would like to introduce a feature that enables users to customize the look and feel of their launcher through the addition of launcher themes. Themes provide users with a way to personalize their experience, allowing them to choose from a variety of designs, color schemes, and styles to suit their preferences.

**Benefits of Launcher Themes** :
1. *Enhanced User Experience*: Themes offer a visual customization option, enhancing user satisfaction and engagement with the launcher. A vibrant theme ecosystem that allows users to express their individuality.
2. *Increased User Retention*: Personalization features like themes can contribute to higher user retention rates, as users are more likely to stick with a launcher that reflects their individual style. Increased community engagement through theme contributions and discussions.
3. *Community Engagement*: The addition of themes can foster creativity within the community, encouraging developers and designers to contribute their unique designs. Positive impact on user satisfaction and retention.

I am eager to hear your thoughts on this proposal and welcome any feedback. Together, I believe we can enhance the Pop Launcher experience and create a more dynamic and user-friendly platform for our PopOS community.

**Comment by jacobgkau** [comment]
This repository is only for the launcher backend; nothing visible (and therefore nothing themeable) is located here. The frontend is implemented in https://github.com/pop-os/shell for the GNOME Shell-based Pop!_OS interface, and https://github.com/pop-os/cosmic-launcher for the Rust-based [COSMIC Epoch](https://github.com/pop-os/cosmic-epoch) interface that's in development.

COSMIC Epoch has themeability as one of its design goals, so the launcher in the COSMIC Epoch session will likely be themeable along with the rest of the interface when it's eventually complete.
