### ISSUE TITLE
Building with "just"

### ISSUE THREAD

**Issue by meerfrau** [pop-os/launcher#197]
When building [for Arch](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pop-launcher) by

prepare() {
  cd "launcher-$pkgver"
  export CARGO_HOME="$srcdir/cargo-home"
  export RUSTUP_TOOLCHAIN=stable
  just vendor

  sed -i 's|{{bin_path}}|/usr/bin/pop-launcher|g' justfile
}

build() {
  cd "launcher-$pkgver"
  export CARGO_HOME="$srcdir/cargo-home"
  export RUSTUP_TOOLCHAIN=stable
  just vendor=1
}

I'm getting `error: Variable `vendor` overridden on the command line but not present in justfile`

Do you ask to build the pop_os launcher with https://github.com/casey/just or is this totally against your will?

**Comment by mmstick** [comment]
Not sure what you're asking exactly, but this project uses just: https://github.com/pop-os/launcher/blob/master/justfile

**Comment by mmstick** [comment]
You should report packaging issues to whomever maintains the package for Arch.
