### ISSUE TITLE
Pop launcher installed correctly but not working [Fedora 37]

### ISSUE THREAD

**Issue by PrimalPimmy** [pop-os/launcher#199]
As the title says, I built it from source, but the launcher is still empty if I try to type in something. And while trying to run it in the terminal, I get 
![image](https://github.com/pop-os/launcher/assets/23097199/42ed20c2-0d9f-46de-9fe6-8126982ff047)

NOTE: Im using pop-shell provided in the fedora repo, I hope nothing else must be done.

**Comment by ltsuda** [comment]
I think I got the same or similar issue.

Installed Pop-os shell on Ubuntu 22.04 LTS through make local-install, launcher open but can't find any app.

```
nov 02 17:31:33 <hostname> gnome-shell[10263]: pop-shell: [DEBUG] starting pop-launcher service
nov 02 17:31:33 <hostname> gnome-shell[10263]: pop-shell: [ERROR] failed to spawn pop-launcher: GLib.SpawnError: Failed to execute child process “pop-launcher” (No such file or directory)
```

**Comment by jacobgkau** [comment]
@ltsuda Your issue looks like you installed `pop-shell` but not `pop-launcher`. `pop-shell` only provides a frontend; the `pop-launcher` app in this repo provides the backend and must also be installed. I don't think that's the same issue that @PrimalPimmy is having, since your issue doesn't mention a cache file.

@PrimalPimmy Is there anything in `~/.cache/pop-launcher/`? If it doesn't exist, are your filesystem permissions configured in a way allowing that directory to be created?

**Comment by ltsuda** [comment]
> @ltsuda Your issue looks like you installed `pop-shell` but not `pop-launcher`. `pop-shell` only provides a frontend; the `pop-launcher` app in this repo provides the backend and must also be installed. I don't think that's the same issue that @PrimalPimmy is having, since your issue doesn't mention a cache file.
> 
> @PrimalPimmy Is there anything in `~/.cache/pop-launcher/`? If it doesn't exist, are your filesystem permissions configured in a way that would allow that directory to be created?

Ohh, understood. It makes sense now, I will try to build from pop-launcher repository as I think there aren't any `.deb` package for Ubuntu available.

Thank you.

**Comment by shreyassanthu77** [comment]
I have the same issue. I am on fedora 39
![image](https://github.com/pop-os/launcher/assets/58223424/77f8eced-2929-4ed6-a43a-ef316679ff3c)
![image](https://github.com/pop-os/launcher/assets/58223424/f5598539-cd23-4ef5-8305-d9ddfd7acdf7)

**Comment by xuesoso** [comment]
there are two issues at play.

1. `pop-launcher` requires a front-end application call to work:
- i.e. call it from `pop-shell` superkey command for launcher.

2. make sure `pop-launcher` binary is installed / symlinked to a system search path:
- for `pop-launcher` to work with the `pop-shell` extension on Fedora / Ubuntu, you need to make sure that `pop-launcher` is accessible as a command on terminal. The default build instruction installs a binary file to `~/.local/bin/pop-launcher`, which is not on system search path. To fix it, create a symlink `sudo ln -s ~/.local/bin/pop-launcher /usr/local/bin/pop-launcher`. Now when you evoke `pop-launcher` through the front end app, a window should pop and the applications should show.

**Comment by nezia1** [comment]
>     * for `pop-launcher` to work with the `pop-shell` extension on Fedora / Ubuntu, you need to make sure that `pop-launcher` is accessible as a command on terminal. The default build instruction installs a binary file to `~/.local/bin/pop-launcher`, which is not on system search path. To fix it, create a symlink `sudo ln -s ~/.local/bin/pop-launcher /usr/local/bin/pop-launcher`. Now when you evoke `pop-launcher` through the front end app, a window should pop and a list of applications should show.

This fixed it for me! We should probably add this to the install script (or perhaps is it in there already?). Had the same issue on Fedora 39.

**Comment by mmstick** [comment]
The pop-launcher package should be storing the binary in `/usr/bin/`. If you are installing it from source, you can change the prefix to place it in `/usr/bin`.

**Comment by nezia1** [comment]
> The pop-launcher package should be storing the binary in `/usr/bin/`. If you are installing it from source, you can change the prefix to place it in `/usr/bin`.

I tried changing the prefix using `sudo just prefix=/usr/local/bin install` but it did not work. It gave me `error: Variable \`prefix\` overridden on the command line but not present in justfile`

Also you mentioned that it should be storing the binary in /usr/bin, but it did place it in `~/.local/bin` for me (regardless of running it as root or as user). Is this expected behavior?

**Comment by Gusfit1** [comment]
@xuesoso 

`sudo ln -s ~/.local/bin/pop-launcher /usr/local/bin/pop-launcher`

Worked for me with EndeavourOS after alt+f2 r'ing. Thanks for the tip!
