### ISSUE TITLE
Support OnlyShowIn and NotShowIn

### ISSUE THREAD

**Issue by friday** [pop-os/launcher#20]
Desktop Entries allow apps to specify that they should show conditionally based on the Desktop Environment, using `OnlyShowIn` and `NotShowIn`

https://specifications.freedesktop.org/menu-spec/latest/ar01s03.html

I have XFCE installed and see those apps from running Gnome

![Screenshot from 2021-09-13 21-21-00](https://user-images.githubusercontent.com/515120/133144881-355efdb0-1982-4ae3-a4b1-9fbf7d3c45f0.png)

The top one for example is /usr/share/applications/xfce4-power-manager-settings.desktop which specify `NotShowIn=GNOME;KDE;Unity;`

If you want this change I could try to implement it.

**Comment by mmstick** [comment]
Sure, yes, in `plugins/desktop-entries`
