### ISSUE TITLE
Custom configurations in `config.ron` file get reverted after updates

### ISSUE THREAD

**Issue by shivamksharma** [pop-os/launcher#201]
I've encountered an issue where modifications made to the `config.ron` file within `/usr/lib/pop-launcher/plugins/web/` are being reverted after system updates or changes made by the launcher. This file contains rules for web searches, and when I add custom configurations, such as `chat.openai.com`, they seem to get reset to default values after some time.

Purpose of Modification:
The reason for modifying the `config.ron` is to refine the search engine configurations presented in the Pop!_OS launcher. The intent behind customizing this file is to enhance efficiency by prioritizing and including more relevant search engines or removing less pertinent ones. For instance, by removing or reordering search engines, I aim to ensure that when typing specific keywords (e.g., "brave"), the launcher suggests the most relevant action (e.g., opening the Brave Browser) rather than displaying a less relevant search engine. The expected outcome of modifying the `config.ron` file is to fine-tune the launcher's search engine suggestions, providing quicker access to frequently used websites or actions, thereby improving the user experience and productivity.

**Steps to Reproduce:**
1. Edit the `config.ron` file to add custom configurations.
2. Observe changes persist until an update or certain period passes.
3. Notice that the custom configurations revert to default settings.

**Expected Behavior:**
Custom configurations in the `config.ron` file should persist across updates or changes made by the launcher, ensuring that the added search rules remain intact.

**Actual Behavior:**
Custom configurations added to the `config.ron` file are reverted to default settings after system updates or possibly at regular intervals without user intervention.

**Additional Information:**
- Pop!_OS version: 21.04
- Launcher version: latest

It would be beneficial if the `config.ron` file could retain custom configurations consistently across updates, ensuring that user-defined settings remain unaffected by system changes. This behaviour significantly impacts users who rely on customizing these configurations for their workflow efficiency.

**Comment by mmstick** [comment]
This file isn't meant to be edited. It's provided by the package. Custom plugin configurations should be stored in `~/.local/share/pop-launcher` or `/etc/pop-launcher/`. See https://github.com/pop-os/launcher/blob/master/src/lib.rs#L16-L39. You can move your config to `~/.local/share/pop-launcher/plugins/web`.

**Comment by shivamksharma** [comment]
Thank you for your guidance regarding the configuration file location. However, the suggested move didn't address the issue I'm encountering. My intention is to remove certain irrelevant search engines and incorporate custom ones, which I've been unable to achieve through relocating the configuration.

I'm still encountering difficulties in achieving the desired outcome. Are there specific steps or additional way you could provide to assist in customizing the search engines within the launcher effectively?

Any further pointers or insights into resolving this issue would be greatly appreciated.

Thank you for your support !
