### ISSUE TITLE
Click on window focuses desktop

### ISSUE THREAD

**Issue by Microwave-WYB** [pop-os/launcher#202]
On Ubuntu 23.10, when the extension is active, clicking a window will focus the desktop instead. You have to click again to focus the application.

https://github.com/pop-os/launcher/assets/68882116/047a5990-5a93-40b8-b4f3-2452db6aa5f7

Here is what happened.

**Comment by mmstick** [comment]
Wrong repo. This is a background service that the launcher in pop-shell launches.
