### ISSUE TITLE
[Web Plugin] Custom keywords resets to default ones upon an update to the launcher

### ISSUE THREAD

**Issue by senntore** [pop-os/launcher#223]
We can edit `/usr/lib/pop-launcher/plugins/web/config.ron` for adding custom keywords, like d for duckduckgo rather than ddg(the default one).
But this change in file, automatically reverts back to it's default state upon an update to the launcher.

This would not be an issue if the config for these plugins were in the home directory(~/.local/share/pop-launcher/plugins).

**Comment by mmstick** [comment]
That is expected, and you can set your custom entries in your local config file.

**Comment by senntore** [comment]
Oh! That's great to know. I thought copying the config in the local config directory for plugins would not work but it is working.
