### ISSUE TITLE
Appearance issue (theme?) / colors / text alignment

### ISSUE THREAD

**Issue by squalou** [pop-os/launcher#224]
Hi,

I did just install successfully from sources, things work fine except for the aspect.

I don't manage to have a proper screenshot, so if I sum up 

- icons, text, and keyboard shortcuts are all centered in the box
- selected text is almost same color as background color - at first I thought text was missing

I wonder how to customize / configure those.

For the records I'm trying this on a fedora 40 distro with gnome and dark theme. (light theme by the way does not change colors either : pop-launcher is always dark, with suites me)

I open it with pop-shell gnome extension. Maybe this issue belongs there ?

Expected : 

``` 
-----------------------------------------------------------
 [icon] My Application                      Ctrl 1
 [icon] Other                                      Ctrl 2
-----------------------------------------------------------
```

Actual result
```
----------------------------------------------------------
            [icon] My Application Ctrl 1
                  [icon] Other Ctrl 2
----------------------------------------------------------
```

**Comment by squalou** [comment]
at least colors comes from what is now referred to as "legacy app theme" in gnome 46 tweaks.

I managed to set  another theme which makes colors readable, but not alignment. That's better.

I'll probably wait for full cosmic-epoch DE to have better :)

**Comment by mmstick** [comment]
This is a service. It doesn't have a GUI. Perhaps you meant to create an issue for pop-shell

**Comment by mmstick** [comment]
> I'm trying this on a fedora 40

I'd recommend trying COSMIC proper at https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/

**Comment by squalou** [comment]
indeed, waiting for cosmic-epoch release, already tried alpha but too many things are not yet ready.

As you mentioned the issue is not in this project but in the gnome-shell extension GUI, I managed something usable with pop-dark theme, apparently Gnome did *again* change (break)  something between 41 and 46 ... anyway for now it will do the trick.

Thanks, 

closing (forgot to with my previous message :) )

**Comment by mmstick** [comment]
Feature-wise, everything is ready for the alpha right now. Only UX and bug polishing remains.

**Comment by squalou** [comment]
Mmh, maybe I misunderstood.
I'm soooo waiting for the full Cosmic-epoch DE that I didn't even consider to try the launcher alone. That's probably what you suggest ?

(to tell the whole story I'm fiddling with a Mac test machine, and building the whole thing from source didn't cross my mind but why not).

Thanks for the suggestion !
