### ISSUE TITLE
[COSMIC Epoch; regression] Search results don't show apps when too many windows are open

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/launcher#228]
This seems to be caused by 172532056b404923b0bc068b524b23e81a371f18. It does not happen on ab7a71a057e3e2ce5fc200b056799a07cf3a9bb5. (FYI, @wiiznokes in case you have an idea of why this might be happening.)

Previously, search results would return application names even if a lot of windows are open:

![screenshot-2024-07-17-14-20-20](https://github.com/user-attachments/assets/aa95c212-193b-448a-8e15-b0953d4d9d7f)

On the latest commit, searching for the same string, I'm getting a bunch of irrelevant (but presumably closest-matching) window results, and no application results:

![screenshot-2024-07-17-14-21-46](https://github.com/user-attachments/assets/161fcd4f-706b-44eb-9d92-8dc22cec982f)

This essentially breaks launching apps with the launcher once more than 8 windows are open.

The good news is, this is not happening in the GNOME session (which is why I didn't catch it during regression testing).

**Comment by mmstick** [comment]
It's a difference in behavior between the cosmic and the pop-shell launcher plugins.

**Comment by wiiznokes** [comment]
This is because the new commit match more field of the desktop entries. In this case, it will match the "internet" categorie of firefox.

Somehow, `strsim::jaro_winkler("terminal", "internet");` return a score of `0.66`, which is a lot. The plugin accept match > `0.6`.

I'm not sure the best way of fixing this. This is kinda related to https://github.com/pop-os/cosmic-launcher/issues/145. Maybe is would make sense to use different matching algorithm for different field. Like using a substring algo for Categories.

**Comment by wash2** [comment]
> Maybe is would make sense to use different matching algorithm for different field. Like using a substring algo for Categories.

Ya, I think that could work. Alternatively, requiring a higher score like 0.8 for matching the desktop entry, and a lower score like 0.6 for matching title and app id in the toplevel plugin seems to work pretty well too.

**Comment by wiiznokes** [comment]
> > Maybe is would make sense to use different matching algorithm for different field. Like using a substring algo for Categories.
> 
> Ya, I think that could work. Alternatively, requiring a higher score like 0.8 for matching the desktop entry, and a lower score like 0.6 for matching title and app id in the toplevel plugin seems to work pretty well too.

https://github.com/pop-os/freedesktop-desktop-entry/pull/22 does smtg like this
