### ISSUE TITLE
`sh` shebang in bundled scripts

### ISSUE THREAD

**Issue by Triton171** [pop-os/launcher#233]
The bundled scripts (for logging out, rebooting, etc.) use `#!/usr/bin/sh` as a shebang which doesn't work on NixOS (or other distributions that are not [FHS](https://de.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)-compliant). Replacing it by `#!/usr/bin/env sh` should work everywhere. If that's fine with you, I'll create a PR to update the scripts. If not, just close the issue and we can patch this downstream.

**Comment by lilyinstarlight** [comment]
(For what it's worth, nixpkgs already has tooling that handles this downstream automatically for derivations, e.g. it does it for our existing pop-launcher derivation at <https://github.com/lilyinstarlight/nixos-cosmic/blob/25b1f07bda7a649ec4230782e839b427ee89474f/pkgs/pop-launcher/package.nix>)

**Comment by Drakulix** [comment]
> Replacing it by #!/usr/bin/env sh should work everywhere. If that's fine with you, I'll create a PR to update the scripts.

Feel free to make a PR, I don't see a reason why we would want to update this.
