### ISSUE TITLE
Tab Navigation in Launcher List

### ISSUE THREAD

**Issue by fjsalata** [pop-os/launcher#26]
When opening the launcher, with either a list of open windows or by starting to type in the name of an application to start in order to generate a list of suggestions, it is not possible to navigate the list with the TAB key. I know this functionality used to be there, I don't recall exactly when it changed. I am assuming when some functionality was added for filename tab completion that this changed the behavior.

It is very natural to want to tab through the list of items. As it stands now, I have to move my fingers off of home row in order to move to the arrow keys to navigate, or I need to select the item with the ctrl+# option provided, which means I have to look for that option and then type it, which is not as quick for me as just tabbing through the items. The kicker is that SHIFT-TAB works just fine when going through the list in reverse order.

This is on Pop!_OS 21.04 with the latest updates.

**Comment by mmstick** [comment]
This is more related to pop-shell than launcher, but pop-shell's launcher uses tab for autocomplete, so it's already reserved.

**Comment by fjsalata** [comment]
> This is more related to pop-shell than launcher, but pop-shell's launcher uses tab for autocomplete, so it's already reserved.

Are you saying this is expected behavior then, not being able to use tab to navigate the list of items? Or should the issue be moved to the pop-shell? Thanks!

**Comment by mmstick** [comment]
Tab is already being used for autocomplete, so it can't be used for navigation.
