### ISSUE TITLE
Getting no response from `Complete` request

### ISSUE THREAD

**Issue by oknozor** [pop-os/launcher#38]
I am trying to figure out how the `Complete` request works. 
Sending the following, or any indice and never get any response.  
```
[2021-10-10T11:58:17Z DEBUG onagre::app] Handle input : Tab
[2021-10-10T11:58:17Z DEBUG onagre::subscriptions::pop_launcher] wrote request "{\"Complete\":0}\n" to pop-launcher stdin
```

I suppose a `Fill` response is expected but it seems strange to try auto-completing something we already have (the selected desktop entry). 

Can you explain how you use this in the official pop-launcher ? 

By the way is the official pop-launcher client open source ? I did not found it on PopOS github organization.

**Comment by oknozor** [comment]
My bad, I just understood this apply to file navigation only. It might be a good idea to mention this in the crate doc.

**Comment by mmstick** [comment]
The launcher GUI frontend that you see in Pop is in pop-shell. Plugins can ignore a `Complete` request, so no response is expected. The GUI should handle events from the launcher service in a reactive way — responding only when it receives an event from the launcher service.
