### ISSUE TITLE
Spotify (Flatpak) breaks open apps in launcher

### ISSUE THREAD

**Issue by zaunermax** [pop-os/launcher#39]
As the title says - once I open the spotify app (which is a flatpak) the launcher does not show open apps anymore. Once the spotify app is closed, the open apps reappear.

with spotify open:
![image](https://user-images.githubusercontent.com/15246773/136784482-96cfcc63-92cd-47c4-806d-5716ecdeec55.png)

with spotify closed:
![image](https://user-images.githubusercontent.com/15246773/136784734-e19cc2e5-be49-48ad-b7b5-d307e839e1f5.png)

LE: Other flatpak applications work just fine - I have just noticed the spotify app doing that, so it might be the spotify app which is causing the problem :monocle_face:

**Comment by jacobgkau** [comment]
Thank you for the report. I'm closing this as a duplicate of https://github.com/pop-os/shell/issues/1208.
