### ISSUE TITLE
Packaging for other distribution

### ISSUE THREAD

**Issue by oknozor** [pop-os/launcher#40]
I am aware this is a bit out of scope but since I rewrote [onagre](https://github.com/oknozor/onagre) as suggested by @mmstick to use pop-launcher, I will soon want to package it for various distros (starting with ubuntu). This would require a pop-launcher package on the target distros. 

I have very little knowledge about packaging for linux distributions other than arch.
I'd be willing to maintain an ubuntu package but I would need some guidance.

Also, as I understand pop-shell is planning to integrate in gnome in the future so you might want to maintain it yourself. 

Let me know.

**Comment by mmstick** [comment]
Maybe not `curl`, but `git clone` then `dpkg-buildpackage -b` and `dpkg -i`
