### ISSUE TITLE
[Feature request] - Per rule icon for web plugin

### ISSUE THREAD

**Issue by oknozor** [pop-os/launcher#41]
I would be nice to have an optional per rule icon for the web plugin, falling back to the default one when not specified :

```
        (
            matches: ["arch"],
            queries: [(name: "Arch Wiki", query: "wiki.archlinux.org/index.php/" )],
            icon: Name("archlinux")
        ),
        (
            // Should fallback to the icon defined in plugins/web/config.ron
            matches: ["bc", "bandcamp"],
            queries: [(name: "Bandcamp", query: "bandcamp.com/search?q=")]
        ),
```

**Comment by mmstick** [comment]
The plugin

**Comment by oknozor** [comment]
Would you want the url to the favicon to be sent or the raw image ?

**Comment by mmstick** [comment]
The plugin can download the favicon to `~/.cache/pop-launcher/`, and give the path to the icon to the launcher.

**Comment by mmstick** [comment]
Unsure how much of a difference in binary size that reqwest makes compared to isahc.
