### ISSUE TITLE
Separate launcher from pop-shell

### ISSUE THREAD

**Issue by dakontiva** [pop-os/launcher#43]
Currently, disabling pop shell extension also disables the launcher (after reboot, somehow launcher works until reboot). It would be better if the launcher is a separate extension and not integrated into the pop shell extension. I don't use tiling functionality but wouldn't bother disabling extension but had to because of this https://github.com/pop-os/shell/issues/1067. However, disabling the pop shell extension also disabled the pop launcher functionality.

**Comment by mmstick** [comment]
Eventually https://github.com/pop-os/cosmic-launcher
