### ISSUE TITLE
Add Installation instructions to README

### ISSUE THREAD

**Issue by nielsonrolim** [pop-os/launcher#49]
As the pop-launcher service has been separated from pop-shell, when you make a local install of pop-shell, you don't have the Launcher available anymore.

Please, add detailed instructions of how to install pop-launcher service and integrate it with pop-shell.

**Comment by Ramblurr** [comment]
On Fedora 35 I had to install `rust cargo gtk3-devel`. `make` and `make install` succeeded, but now I'm not sure what to do?

How do I use it?

**Comment by mmstick** [comment]
The launcher is just a JSON IPC service, so you need a frontend for it. In Pop!_OS the default frontend is the one provided by pop-shell.

**Comment by Ramblurr** [comment]
Ah yea, I figured as much. I should have been more specific, how to I configure a manually installed pop-shell to use the service? 

Does pop-shell handle execing the service? Should I create  systemd user service to run the launcher in the background?

**Comment by mmstick** [comment]
It's two-way IPC over stdin and stdout, and pop-shell will launch the process when the launcher is opened, and exit the process when it is closed.

**Comment by prasannavl** [comment]
On debian/ubuntu, just do `make` with valid rustc and gcc, letting the errors guide on what `lib*-dev` pkgs to install until this is documented. 

On my fresh(-ish) existing setup, deps looked something like this:   

```
libcairo2-dev libgdk-pixbuf2.0-dev libatk1.0-dev libpango1.0-dev libgtk-3-dev
```

**Comment by mmstick** [comment]
For what it's worth, `libgtk-3-dev` installs all of those dependencies automatically.

**Comment by marcelobelli** [comment]
@Ramblurr about Fedora, you had to put the `.local/bin/` in your `PATH` so the pop-shell can find the launcher binary. For me that was the missing piece to make it work

**Comment by JJGadgets** [comment]
> @Ramblurr about Fedora, you had to put the `.local/bin/` in your `PATH` so the pop-shell can find the launcher binary. For me that was the missing piece to make it work

To install for all users, I ran this make command to install to `/usr` where `/usr/bin` is definitely in `PATH`:
``` shell
make && sudo PWD=$PWD DESTDIR=/ make install
```

**Comment by yochananmarqos** [comment]
Just do it. 

<small>see what I did there? :laughing: </small>
