### ISSUE TITLE
Unable to launch applications

### ISSUE THREAD

**Issue by prasannavl** [pop-os/launcher#58]
On Ubuntu 20.04 LTS with `make` and `make install`: 

```
$ uname -vopr
5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 GNU/Linux

[12:27:41|pvl@pvl-x1:~/src/repos/pop-launcher] (1.0.3)
$ rustc --version
rustc 1.56.0 (09c42c458 2021-10-18)

[12:27:45|pvl@pvl-x1:~/src/repos/pop-launcher] (1.0.3)
$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

Launcher works with `pop-shell`. Can switch between open windows, and search displays list. 

Issues: 
- Hitting "Enter" (or the `Ctrl + x`) on any result other than open windows have no action. 
- Color scheme: Currently highlighted item is dimmed out on dark mode, that's it's not at all visible. 

![image](https://user-images.githubusercontent.com/559409/140635505-e5cf47d2-6e12-48e9-9f34-a56b73ea6357.png)

**Comment by Thysinner** [comment]
I have the same issue on Ubuntu 20.04
```bash
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

```bash
❯ uname -a
Linux station 5.11.0-41-generic #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
❯ rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)
```

```bash
❯ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by benzino77** [comment]
Same here. Ubuntu 20.04 on Wayland. Launcher (make && make install) and pop!_shell (make local-install) installed from sources.
pop!_shell: commit de901ae4cc21dcce3613ef0f4c53c2242230f645
launcher: commit 98e386621e876b1a1322a1c89e2951d7f29f2b82
```shell
$ sb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
$ rustc --version
rustc 1.53.0
$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
```

there is this information on journal logs:
```
JS WARNING: [/home/benzino/.local/share/gnome-shell/extensions/pop-shell@system76.com/launcher.js 162]: reference to undefined property "AppLaunchGpu"
```
- I can switch between open windows
- I can do web search by entering: `ddg is duckduckgo bettern than google?`
- I can use calculator by entering: `2+2`
- I can do file navigation
- I can do file search
- I can run commands on terminal, but only when I enter full command i.e.: `run ranger`. I cannot choose a command from the list (the list which appears when I start  typing `run`)
- **I can't start application by entering its name and choosing it on the list**

**Comment by benzino77** [comment]
This is a gnome-shell 3.36 problem.

Applying this https://github.com/pop-os/shell/pull/1205 to pop-shell, solves problem.
