### ISSUE TITLE
[Ubuntu 20.04] Launcher no longer shows opened windows

### ISSUE THREAD

**Issue by pesader** [pop-os/launcher#64]
When I recently updated the launcher, it stopped showing opened windows. As you can see in the screenshot below, I have Calendar, Firefox, Inkscape and Alacritty opened, but none show in the launcher. Search is working normally.

![image](https://user-images.githubusercontent.com/65264536/142767983-436e43b2-a694-4c61-a26a-36cced65fe32.png)

**System info**
Ubuntu 20.04
GNOME 3.36.9

**Latest commit**
ed38f3a: chore!: Remove deprecated `IconSource::Window`

**Steps to reproduce**
- Rebuild and install the launcher from this commit ed38f3a
- Log out of your session and log back in
- Open some windows
- The launcher won't show the windows you've opened

**Comment by mmstick** [comment]
You have to update Pop Shell too. The ! in the commit tag indicates breaking change.

**Comment by pesader** [comment]
Hi! I took your advice and updated pop shell as well. Logged off and logged back in to unfortunately find the same issue:

![image](https://user-images.githubusercontent.com/65264536/142790728-795c3a4e-1ad3-44b1-b6ac-2e7f20df7552.png)
