### ISSUE TITLE
When does launcher re-load all plugins?

### ISSUE THREAD

**Issue by canadaduane** [pop-os/launcher#68]
I'm writing my first launcher plugin. It isn't working. But I'm not sure if it isn't working because I don't know how to restart the launcher, or if I don't know where to look for logs.

Does the launcher read from all directories automatically, or is there a "reload" step?

If I've done something horribly wrong, how would I know (for example a .ron syntax error, or a missing bin executable)?

**Comment by jacobgkau** [comment]
> But I'm not sure if it isn't working because I don't know how to restart the launcher

If you're using pop-launcher with the pop-shell frontend, then the pop-launcher process should be spawned when you open the Launcher frontend, and the process should exit when you close the Launcher frontend. Closing and re-opening the Launcher would restart the process.

> Does the launcher read from all directories automatically, or is there a "reload" step?

After removing the `calc` directory from `/usr/lib/pop-launcher/plugins/`, the Launcher does not show the calculator plugin next time it's opened. Adding it to `~/.local/share/pop-launcher/plugins/`, I'm seeing it not work, but `/etc/pop-launcher/plugins/` does work. Can you confirm if your plugin works if you place it in one of the system-wide directories?
