### ISSUE TITLE
Launcher not seeing plugins

### ISSUE THREAD

**Issue by eiis1000** [pop-os/launcher#7]
The pop launcher seems to not be seeing any plugins, including the default ones. In my launcher directory I have the following:
![image](https://user-images.githubusercontent.com/59699534/132112046-de99f6d1-e9f8-42a2-92b0-0ab8543d1514.png)

But when I open the launcher, `=1+1` yields no results, and `?` only shows file search as done using `file [FILENAME]`, which does work (unlike `google bananas` or anything along those lines). I'd include a screenshot, but doing so stops the launcher.

**Comment by mmstick** [comment]
Did you restart GNOME Shell after this update?
