### ISSUE TITLE
Add to launcher

### ISSUE THREAD

**Issue by qaqak** [pop-os/launcher#76]
I added an app to the GNOME app list, but it is not showing up in the Launcher.
How can I manually add an app to the GNOME app menu and launcher?

**Comment by jacobgkau** [comment]
The Launcher reads .desktop files from several locations and filters them based on the logic in the plugin file: https://github.com/pop-os/launcher/blob/master/plugins/src/desktop_entries/mod.rs 

How did you add the app to the GNOME app list? Where did you place the .desktop file and what is its contents?

**Comment by qaqak** [comment]
`/usr/share/applications/`
I just put some Android Studio info there

**Comment by jacobgkau** [comment]
Please share the contents of the `.desktop` file like I requested. That way, I can confirm the syntax is valid and test it on my own system to see what the issue might be.

**Comment by qaqak** [comment]
I don't know the exact contents, but I it was something like this:
```
[Desktop Entry]
Version=1.0
Name=Android Studio
Exec=/home/qaqak/Apps/AndroidStudio/bin/studio.sh
Icon=/home/qaqak/Apps/AndroidStudio/bin/studio.png
Type=Application
Terminal=false
```
Yeah, something like that

**Comment by jacobgkau** [comment]
Can you please run `cat` on the file so you can show what's actually in it?

**Comment by qaqak** [comment]
I, uh, deleted it...

**Comment by jacobgkau** [comment]
I placed the output you gave in the location you stated, and the Launcher shows the icon:

![Screenshot from 2022-01-03 09-17-23](https://user-images.githubusercontent.com/7199422/147954007-73f8d8fc-667d-48b3-b04e-695f6493a80b.png)

Please re-open the issue if you are able to recreate it again.

**Comment by qaqak** [comment]
Okay for a reason it finally worked. I don't know what the problem was, but if it works, don't touch it. Sorry for the confusion!

**Comment by qaqak** [comment]
But I have another question.
I get that when it says System, it's a desktop file in `/usr/share/applications`.
When it says Flatpak, it's a flatpak.
When it says Snap(System), it's a Snap
But how do you get it to say Local?

**Comment by jacobgkau** [comment]
>  But how do you get it to say Local?

Place it in `~/.local/share/applications` (where `~` is your home directory).
