### ISSUE TITLE
i installed pop-shell and pop-launcher but nothing shows up when i type in the launcher

### ISSUE THREAD

**Issue by nobodyatandnothing** [pop-os/launcher#77]
are there any dependencies that i may be missing ?

**Comment by caioolivv** [comment]
Did you figure it out? I'm having the same issue on Fedora 36

**Comment by varunbpatil** [comment]
For anybody else wondering why it is not working after manually installing pop-shell and pop-launcher, pop-launcher needs to be in the `PATH` after installation. For me, pop-launcher was installed in `~/.local/bin`. I just created a symlink to it in `/usr/local/bin`.
