### ISSUE TITLE
Launcher does not start the application 

### ISSUE THREAD

**Issue by Deottive** [pop-os/launcher#81]
I have installed launcher with `make && make install ` and when I press the default keybinding it does pop up and when I search also shows the app and everything works fine until then but whenever I press enter to open the selected app the launcher does not open the app. 
Although when I install the launcher using the command it does shows some errors 
![image](https://user-images.githubusercontent.com/71910027/149074427-f37c3b23-a00c-4b9d-8f41-b984dc4b25ea.png)

I wish you reply

OS - Ubuntu 20.04

**Comment by localjo** [comment]
Launcher also stopped working for me after installing all available updates in Pop!_Shop. It won't open via super shortcut, or via the icon.

**Comment by ftorres16** [comment]
Hi! I am also facing the same issue. I see that this issue is closed but fix or workaround. Could you fix your issue?
