### ISSUE TITLE
Web plugin breaks http links

### ISSUE THREAD

**Issue by purrie** [pop-os/launcher#92]
I noticed that the web plugin always tries to use https even when supplied with a link that uses http. I have a situation where I want to use the launcher to quickly access a server on my local host, which uses http but the plugin adds https in front of it, thus, breaking the link. I would be thankful to see this issue fixed.

**Comment by mmstick** [comment]
What website only supports http and not https?

**Comment by purrie** [comment]
On the internet I can't think of any relevant examples. 

I have two example uses on the local network tho. First one is a web server I develop as a learning and personal use project that lives in my local network that I don't need to use https for but I would like to have quick access to it through the launcher. Second is yacy search engine which also can live as a local server and it uses http. I thought requesting http support for the launcher makes more sense than trying to upgrade both servers to support https.

**Comment by mmstick** [comment]
Please try the `launcher` branch and see if that works for you.

**Comment by purrie** [comment]
It works perfectly. Thanks.
