### ISSUE TITLE
Desktop entries plugin: unknown cmd

### ISSUE THREAD

**Issue by MKuranowski** [pop-os/launcher#98]
I'm running version 1.2.0 (commit bacada02c23ab7df021f8b8ead7470df09443cb5) on an Arch machine, and I'm seeing no desktop entries in the launcher GUI.

After some investigation, running the `desktop_entries` plugin doesn't work, the binary spits out the following error:
```
unknown cmd: pop-launcher-bin
```
and exits without any error codes.

Reproduced both when installed from AUR and on a fresh clone.

<details>
  <summary>Reproduce steps</summary>

  ```console
  $ just
  ...
  $ cd target/release
  $ ln -s pop-launcher-bin desktop_entries
  $ ./desktop_entries
  unknown cmd: desktop_entries
  $ echo $?
  0
  ```

</details>

**Comment by MKuranowski** [comment]
My educated guess is that this bug is introduced by the switch to justfiles (https://github.com/pop-os/launcher/commit/2c7af23323f533cdcec252fc02ea35b80f8df428)

The Makefile replaced `_` to `-` in the plugin names for the binary symlink (https://github.com/pop-os/launcher/blob/d17acbd9ce858748136a7268d4a9bf43d4b97907/Makefile#L66)

While the just file doesn't do that: https://github.com/pop-os/launcher/blob/master/justfile#L63

**Comment by mmstick** [comment]
Use the launcher branch
